site_name: "SỔ TAY KHÁM BỆNH, CHỮA BỆNH EMR"
theme:
  name: material
  language: vi
  palette:
    - scheme: default
      primary: blue        # màu chủ đạo
      accent: teal         # màu nhấn
    - scheme: slate        # chế độ dark mode
      primary: blue
      accent: teal
      toggle:
        icon: material/weather-night
  font:
    text: Roboto
    code: Fira Code
  custom_dir: overrides
nav:
  - Giới thiệu: 0.intro.md
  - 1. Điều trị Ngoại trú: 
      1.1. Khám và chỉ định: 1.1.khamvachidinh.md
      1.2. Xem và ký số kết quả CLS: 1.2.xemCLS.md
      1.3. Hướng xử lý:  
        1.3.1. Chuyển phòng: 1.3.1.chuyenphong.md
        1.3.2. Cấp toa cho về: 1.3.2.captoachove.md
        1.3.3. Nhập viện: 1.3.3.ten.md
        1.3.4. Chuyển tuyến: 1.3.4.ten.md
        1.3.5. Điều trị BA ngoại trú: 1.3.5.ten.md
        1.3.6. Hội chẩn: 1.3.6.ten.md
  - 2. Điều trị Nội trú: noitru.md
  - 3. Tiện ích:
      3.1. Phần mềm scan: 3.1.phanmemscan.md 
      3.2. Làm mới phần mềm KCB: 3.2.lammoiphanmem.md 
extra_css:
  - styles/extra.css
